### ISSUE TITLE
Should the full_mask / bitmask distinction work when used via stdlib?

### ISSUE THREAD

**Issue by jhorstmann** [rust-lang/portable-simd#307]
I tried this code:

```rust
#![feature(portable_simd)]

pub fn main() {
    println!("{}", std::mem::size_of::<std::simd::mask64x8>());
    println!("{}", std::mem::size_of::<core_simd::mask64x8>());
}
```

When run with `RUSTFLAGS="-Ctarget-cpu=native"` on my tigerlake machine the output is

```
64
1
```

This seems to indicate that when used via the standard library, the optimized code path for avx512 mask registers is not used.

Adding `-Z build-std --target x86_64-unknown-linux-gnu` to the command line prints `1` for `std::simd::mask64x8`.

Would this then be the recommended way to get best performance, should we continue using `core_simd` as a crate dependency or is there maybe another solution?

### Meta

```
$ rustc +nightly --version
rustc 1.66.0-nightly (81f391930 2022-10-09)
```

```toml
[dependencies]
core_simd = { git = "https://github.com/rust-lang/portable-simd", optional = true, rev = "2c5ebfb6a26d384bc21db6796095890c1f13f19c" }
```
